### ISSUE TITLE
intellij error

### ISSUE THREAD

**Issue by ghost** [plex1/SpinalDev#1]
Hi!

The command '/bin/sh -c wget https://download.jetbrains.com/idea/ideaIC-$INTELLIJ_VER.$INTELLIJ_SUBVER.tar.gz -O /tmp/intellij.tar.gz -q &&     mkdir -p /opt/intellij &&     tar -xf /tmp/intellij.tar.gz --strip-components=1 -C /opt/intellij &&     rm /tmp/intellij.tar.gz' returned a non-zero code: 8

Is there anyway to fix and continue from this point?

**Comment by plex1** [comment]
Hello

You are right, thanks for the info. Apparently jetbrains.com took that particular version of intellij from their website. If you set INTELLIJ_SUBVER=5 it works. It is updated in the latest commit.
